spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234

#开启驼峰命名法和下划线的自动转化
mybatis:
  configuration:
    map-underscore-to-camel-case: true